apiVersion: v1
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  proxy-body-size: "64m"
  use-proxy-protocol: "true"
  hsts-include-subdomains: "false"
  server-name-hash-bucket-size: "256"
kind: ConfigMap
metadata:
  name: nginx-configuration
