apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: operationcode-backend
spec:
  replicas: 2
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: operationcode-backend
    spec:
      containers:
      - name: app
        image: operationcode/operationcode_backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: postgres_password
        - name: AIRTABLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: airtable_api_key
        - name: SLACK_LEGACY_ADMIN_TOKEN 
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_legacy_admin_token 
        - name: AIRTABLE_BASE_ID
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: airtable_base_id
              optional: true
        - name: GIT_HUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: git_hub_client_id
              optional: true
        - name: GIT_HUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: git_hub_client_secret
              optional: true
        - name: GIT_HUB_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: git_hub_oauth_token
              optional: true
        - name: PY_BOT_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: py_bot_auth_key
              optional: true
        - name: POSTGRES_HOST
          value: opcode-postgres
        - name: REDIS_URL
          value: redis://opcode-redis:6379/0
        - name: RAILS_ENV
          value: production
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: postgres_user
        - name: SLACK_SUBDOMAIN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_subdomain
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_token
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt_secret_key
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: secret_key_base
        - name: SKYLIGHT_AUTHENTICATION
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: skylight_authentication
        volumeMounts:
        - name: backend-secrets
          mountPath: /run/secrets
      - name: operationcode-sidekiq
        image: operationcode/operationcode_backend:latest
        command: ["sidekiq", "-C config/sidekiq.yml.erb"]
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: postgres_password
        - name: POSTGRES_HOST
          value: opcode-postgres
        - name: REDIS_URL
          value: redis://opcode-redis:6379/0
        - name: SLACK_SUBDOMAIN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_subdomain
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_token
        - name: RAILS_ENV
          value: production
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt_secret_key
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: secret_key_base
        volumeMounts:
        - name: backend-secrets
          mountPath: /run/secrets
      volumes:
      - name: backend-secrets
        secret:
          secretName: backend-secrets
