
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: operationcode-backend
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: RAILS_ENV
          value: staging
        - name: SLACK_SERVICE_URL
          value: http://pybot.staging.operationcode.org:8080/pybot/api/v1/slack
      - name: sidekiq
        env:
        - name: RAILS_ENV
          value: staging
        - name: SLACK_SERVICE_URL
          value: http://pybot.staging.operationcode.org:8080/pybot/api/v1/slack
