kind: Namespace
apiVersion: v1
metadata:
  name: operationcode
  labels:
    name: operationcode
---
kind: Namespace
apiVersion: v1
metadata:
  name: operationcode-staging
  labels:
    name: operationcode-staging
---
kind: Namespace
apiVersion: v1
metadata:
  name: nginx-ingress
  labels:
    name: nginx-ingress
