apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: operationcode-backend
spec:
  replicas: 2
  revisionHistoryLimit: 5
  template:
    spec:
      containers:
      - name: app
        image: operationcode/operationcode_backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: postgres_password
        - name: AIRTABLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: airtable_api_key
        - name: SLACK_LEGACY_ADMIN_TOKEN 
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_legacy_admin_token 
        - name: AIRTABLE_BASE_ID
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: airtable_base_id
        - name: GIT_HUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: git_hub_client_id
        - name: GIT_HUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: git_hub_client_secret
        - name: GIT_HUB_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: git_hub_oauth_token
        - name: PY_BOT_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: py_bot_auth_key
        - name: POSTGRES_HOST
          value: opcode-postgres
        - name: REDIS_URL
          value: redis://opcode-redis:6379/0
        - name: RAILS_ENV
          value: production
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: postgres_user
        - name: SLACK_SUBDOMAIN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_subdomain
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_token
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt_secret_key
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: secret_key_base
        - name: SKYLIGHT_AUTHENTICATION
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: skylight_authentication
        - name: SENTRY_CREDENTIALS
          valueFrom:
            secretKeyRef:
              key: sentry_credentials
              name: backend-secrets
        - name: SENDGRID_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: sendgrid_password 
        - name: SENDGRID_USERNAME 
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: sendgrid_username 
        - name: SLACK_SERVICE_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: slack_service_auth_token
              name: backend-secrets   
        - name: SLACK_SERVICE_URL
          value: http://pyback-lb-197482116.us-east-2.elb.amazonaws.com:80/pybot/api/v1/slack
      - name: sidekiq
        image: operationcode/operationcode_backend:latest
        command: ["bundle", "exec", "sidekiq"]
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: postgres_password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: postgres_user
        - name: POSTGRES_HOST
          value: opcode-postgres
        - name: REDIS_URL
          value: redis://opcode-redis:6379/0
        - name: SLACK_SUBDOMAIN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_subdomain
        - name: SLACK_LEGACY_ADMIN_TOKEN 
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_legacy_admin_token 
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: slack_token        
        - name: SENDGRID_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: sendgrid_password 
        - name: SENDGRID_USERNAME 
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: sendgrid_username 
        - name: RAILS_ENV
          value: production
        - name: SENTRY_CREDENTIALS
          valueFrom:
            secretKeyRef:
              key: sentry_credentials
              name: backend-secrets
        - name: SLACK_SERVICE_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: slack_service_auth_token
              name: backend-secrets   
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt_secret_key
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: secret_key_base
        - name: SLACK_SERVICE_URL
          value: http://pyback-lb-197482116.us-east-2.elb.amazonaws.com:80/pybot/api/v1/slack
      volumes:
      - name: backend-secrets
        secret:
          secretName: backend-secrets